import type { BaseClassDefinition } from '../sim/units/UnitDefinitions';

export const BASE_CLASSES: Record<string, BaseClassDefinition> = {
  warrior: {
    identifier: 'warrior',
    displayName: 'Warrior',
    description: 'Front-line fighters who master physical strength and endurance. They hold the line when others fall back and anchor any guild formation.',
    statisticsAtLevelOne: {
      hitPointsMaximum: 30,
      manaPointsMaximum: 8,
      attack: 9,
      defense: 8,
      magicPower: 2,
      magicResistance: 4,
      speed: 7,
      movementRange: 4,
      jumpHeight: 1,
      evasion: 0.05,
    },
    statisticGrowthPerLevel: {
      hitPointsMaximum: 6,
      manaPointsMaximum: 1,
      attack: 2,
      defense: 1.5,
      magicResistance: 0.5,
      speed: 0.4,
    },
    skillIdentifiers: ['power_strike', 'war_cry'],
  },
  thief: {
    identifier: 'thief',
    displayName: 'Thief',
    description: 'Quick and cunning fighters who exploit every opening. Speed and misdirection are their weapons — no guard, lock, or trap can stop a skilled thief.',
    statisticsAtLevelOne: {
      hitPointsMaximum: 24,
      manaPointsMaximum: 10,
      attack: 7,
      defense: 5,
      magicPower: 3,
      magicResistance: 4,
      speed: 10,
      movementRange: 5,
      jumpHeight: 2,
      evasion: 0.15,
    },
    statisticGrowthPerLevel: {
      hitPointsMaximum: 4,
      manaPointsMaximum: 1,
      attack: 1.5,
      defense: 1,
      speed: 0.7,
      evasion: 0.005,
    },
    skillIdentifiers: ['flanking_strike', 'thrown_dagger'],
  },
  mage: {
    identifier: 'mage',
    displayName: 'Mage',
    description: 'Scholars of the arcane who channel the raw forces of the elements. Fragile but devastating at range, their spells reshape the battlefield.',
    statisticsAtLevelOne: {
      hitPointsMaximum: 20,
      manaPointsMaximum: 22,
      attack: 3,
      defense: 4,
      magicPower: 10,
      magicResistance: 8,
      speed: 7,
      movementRange: 3,
      jumpHeight: 1,
      evasion: 0.05,
    },
    statisticGrowthPerLevel: {
      hitPointsMaximum: 3,
      manaPointsMaximum: 4,
      attack: 0.5,
      defense: 0.5,
      magicPower: 2,
      magicResistance: 1.5,
      speed: 0.4,
    },
    skillIdentifiers: ['fire_bolt', 'flame_burst'],
  },
  priest: {
    identifier: 'priest',
    displayName: 'Priest',
    description: 'Healers and holy conduits who channel divine or elemental power. They keep allies standing long after others would have fallen.',
    statisticsAtLevelOne: {
      hitPointsMaximum: 22,
      manaPointsMaximum: 20,
      attack: 4,
      defense: 5,
      magicPower: 8,
      magicResistance: 9,
      speed: 7,
      movementRange: 3,
      jumpHeight: 1,
      evasion: 0.05,
    },
    statisticGrowthPerLevel: {
      hitPointsMaximum: 4,
      manaPointsMaximum: 3.5,
      attack: 0.5,
      defense: 0.8,
      magicPower: 1.5,
      magicResistance: 1.8,
      speed: 0.4,
    },
    skillIdentifiers: ['first_aid', 'sacred_bolt'],
  },
};
