import type { EquipmentDefinition } from '../sim/items/EquipmentDefinition';

/**
 * Store equipment for Wanderer's Rest. Weapons are class-bound; armor and
 * accessories are open to everyone. Some pieces are gated behind a
 * `minimumReputationTier` (see `src/sim/guild/ReputationTier.ts`); rarities
 * beyond tier-gating remain M4 content work.
 */
export const EQUIPMENT: Record<string, EquipmentDefinition> = {
  // ── Weapons ────────────────────────────────────────────────────────────
  iron_sword: {
    identifier: 'iron_sword',
    displayName: 'Iron Sword',
    description: 'Honest smith-work from the Rest. The guild standard.',
    slot: 'weapon',
    priceInGold: 90,
    statisticBonuses: { attack: 3 },
    allowedClasses: ['warrior'],
  },
  steel_greatblade: {
    identifier: 'steel_greatblade',
    displayName: 'Steel Greatblade',
    description: 'Two hands, one argument. Werelizards swear by it.',
    slot: 'weapon',
    priceInGold: 210,
    statisticBonuses: { attack: 6, speed: -1 },
    allowedClasses: ['warrior'],
    minimumReputationTier: 'silver',
  },
  hunting_dagger: {
    identifier: 'hunting_dagger',
    displayName: 'Hunting Dagger',
    description: 'Light, quick, and quiet — a thief’s closest friend.',
    slot: 'weapon',
    priceInGold: 80,
    statisticBonuses: { attack: 2, speed: 1 },
    allowedClasses: ['thief'],
  },
  oak_focus_staff: {
    identifier: 'oak_focus_staff',
    displayName: 'Oak Focus Staff',
    description: 'Cut from a tree that never walked. Steadies the casting hand.',
    slot: 'weapon',
    priceInGold: 95,
    statisticBonuses: { magicPower: 3 },
    allowedClasses: ['mage'],
  },
  blessed_rod: {
    identifier: 'blessed_rod',
    displayName: 'Blessed Rod',
    description: 'Anointed at the shrines. Hums faintly near the wounded.',
    slot: 'weapon',
    priceInGold: 95,
    statisticBonuses: { magicPower: 2, magicResistance: 2 },
    allowedClasses: ['priest'],
  },
  // ── Skill-bearing weapons (PRD §7 — the skill is usable while equipped
  //    and mastered permanently through use; see SkillMastery.ts) ─────────
  greathorn_cleaver: {
    identifier: 'greathorn_cleaver',
    displayName: 'Greathorn Cleaver',
    description: 'An axe bitted with a greathorn boar\'s tusk. The sweep is in the weight — it teaches itself.',
    slot: 'weapon',
    priceInGold: 220,
    statisticBonuses: { attack: 5 },
    allowedClasses: ['warrior'],
    minimumReputationTier: 'silver',
    grantedSkillIdentifier: 'cleaving_arc',
  },
  moonshadow_knife: {
    identifier: 'moonshadow_knife',
    displayName: 'Moonshadow Knife',
    description: 'Werecat knife-craft, quenched under a new moon. The blade remembers the cut its makers favored.',
    slot: 'weapon',
    priceInGold: 200,
    statisticBonuses: { attack: 3, speed: 1 },
    allowedClasses: ['thief'],
    minimumReputationTier: 'silver',
    grantedSkillIdentifier: 'shadow_fang',
  },
  tidecaller_staff: {
    identifier: 'tidecaller_staff',
    displayName: 'Tidecaller Staff',
    description: 'Driftwood blessed at Yiern\'s riverside shrines. It pulls at the water in the air.',
    slot: 'weapon',
    priceInGold: 230,
    statisticBonuses: { magicPower: 4 },
    allowedClasses: ['mage'],
    minimumReputationTier: 'silver',
    grantedSkillIdentifier: 'tide_surge',
  },
  dawnlight_rod: {
    identifier: 'dawnlight_rod',
    displayName: 'Dawnlight Rod',
    description: 'Carried at Hortian dawn services. Those who bear it long enough learn the morning prayer by heart.',
    slot: 'weapon',
    priceInGold: 230,
    statisticBonuses: { magicPower: 3, magicResistance: 1 },
    allowedClasses: ['priest'],
    minimumReputationTier: 'silver',
    grantedSkillIdentifier: 'dawns_mercy',
  },

  // ── Gold-tier weapons (masterwork — PRD §7 item tiers) ─────────────────
  borderwarden_blade: {
    identifier: 'borderwarden_blade',
    displayName: 'Borderwarden Blade',
    description: 'Forged for the wall-watch that holds the safe lands. It has never been on the losing side of a border.',
    slot: 'weapon',
    priceInGold: 400,
    statisticBonuses: { attack: 8, defense: 1 },
    allowedClasses: ['warrior'],
    minimumReputationTier: 'gold',
  },
  galecut_dagger: {
    identifier: 'galecut_dagger',
    displayName: 'Galecut Dagger',
    description: 'Werecat masterwork, sharpened on Breir’s own wind. It arrives before the hand that holds it.',
    slot: 'weapon',
    priceInGold: 380,
    statisticBonuses: { attack: 5, speed: 2 },
    allowedClasses: ['thief'],
    minimumReputationTier: 'gold',
  },
  stormglass_staff: {
    identifier: 'stormglass_staff',
    displayName: 'Stormglass Staff',
    description: 'Sand struck by godless lightning, drawn into a rod. No shrine claims it; it doesn’t seem to mind.',
    slot: 'weapon',
    priceInGold: 420,
    statisticBonuses: { magicPower: 7 },
    allowedClasses: ['mage'],
    minimumReputationTier: 'gold',
  },
  shrinekeepers_crosier: {
    identifier: 'shrinekeepers_crosier',
    displayName: 'Shrinekeeper’s Crosier',
    description: 'Passed keeper to keeper at the old shrines. Every faith that held it left a blessing behind.',
    slot: 'weapon',
    priceInGold: 400,
    statisticBonuses: { magicPower: 5, magicResistance: 3 },
    allowedClasses: ['priest'],
    minimumReputationTier: 'gold',
  },

  // ── Armor ──────────────────────────────────────────────────────────────
  leather_vest: {
    identifier: 'leather_vest',
    displayName: 'Leather Vest',
    description: 'Boiled leather over padding. Better than regret.',
    slot: 'armor',
    priceInGold: 70,
    statisticBonuses: { defense: 2 },
  },
  iron_mail: {
    identifier: 'iron_mail',
    displayName: 'Iron Mail',
    description: 'Heavy rings, heavier confidence.',
    slot: 'armor',
    priceInGold: 160,
    statisticBonuses: { defense: 4, speed: -1 },
    minimumReputationTier: 'silver',
  },
  travelers_garb: {
    identifier: 'travelers_garb',
    displayName: 'Traveler’s Garb',
    description: 'Weathered, loose, and easy to vanish in.',
    slot: 'armor',
    priceInGold: 85,
    statisticBonuses: { defense: 1, evasion: 0.04 },
  },
  warded_plate: {
    identifier: 'warded_plate',
    displayName: 'Warded Plate',
    description: 'Plate armor etched with earth-wards. The Darkness has to knock first.',
    slot: 'armor',
    priceInGold: 350,
    statisticBonuses: { defense: 6, magicResistance: 2, speed: -1 },
    minimumReputationTier: 'gold',
  },
  windwoven_mantle: {
    identifier: 'windwoven_mantle',
    displayName: 'Windwoven Mantle',
    description: 'Cloth with Breir’s breath in the weave. Blows land where the wearer just was.',
    slot: 'armor',
    priceInGold: 320,
    statisticBonuses: { defense: 3, evasion: 0.06 },
    minimumReputationTier: 'gold',
  },
  // ── Accessories ────────────────────────────────────────────────────────
  swift_charm: {
    identifier: 'swift_charm',
    displayName: 'Swift Charm',
    description: 'A werecat token: a knot of wind tied in copper wire.',
    slot: 'accessory',
    priceInGold: 120,
    statisticBonuses: { speed: 2 },
  },
  stout_ring: {
    identifier: 'stout_ring',
    displayName: 'Stout Ring',
    description: 'Taurk-blessed iron. Wearers eat well and fall seldom.',
    slot: 'accessory',
    priceInGold: 110,
    statisticBonuses: { hitPointsMaximum: 8 },
  },
  focus_band: {
    identifier: 'focus_band',
    displayName: 'Focus Band',
    description: 'A cord of prayer-knots that keeps the well of mana deep.',
    slot: 'accessory',
    priceInGold: 110,
    statisticBonuses: { manaPointsMaximum: 6 },
  },
  charm_of_the_eighth_life: {
    identifier: 'charm_of_the_eighth_life',
    displayName: 'Charm of the Eighth Life',
    description: 'A werecat keepsake, one life folded away for later. Nobody sells the ninth.',
    slot: 'accessory',
    priceInGold: 340,
    statisticBonuses: { hitPointsMaximum: 10, evasion: 0.03 },
    minimumReputationTier: 'gold',
  },
  emberglass_pendant: {
    identifier: 'emberglass_pendant',
    displayName: 'Emberglass Pendant',
    description: 'Kosh-fired glass from the pyre shrines. Warm to the touch, deeper than it looks.',
    slot: 'accessory',
    priceInGold: 330,
    statisticBonuses: { magicPower: 2, manaPointsMaximum: 8 },
    minimumReputationTier: 'gold',
  },
};
