import type { MonsterDefinition } from '../sim/units/UnitDefinitions';

/** Creatures twisted by the Darkness (LORE.md) — the M1 enemy roster. */
export const MONSTERS: Record<string, MonsterDefinition> = {
  twisted_wolf: {
    identifier: 'twisted_wolf',
    displayName: 'Twisted Wolf',
    level: 3,
    statistics: {
      hitPointsMaximum: 26,
      manaPointsMaximum: 6,
      attack: 9,
      defense: 5,
      magicPower: 0,
      magicResistance: 3,
      speed: 10,
      movementRange: 5,
      jumpHeight: 2,
      evasion: 0.1,
    },
    canFly: false,
    skillIdentifiers: ['savage_bite'],
    // Twisted wolves burn easily and shy from sacred light.
    elementalAffinities: { fire: 1.5, sacred: 1.25, water: 0.75 },
  },
  stoneling: {
    identifier: 'stoneling',
    displayName: 'Stoneling',
    level: 3,
    statistics: {
      hitPointsMaximum: 40,
      manaPointsMaximum: 6,
      attack: 10,
      defense: 11,
      magicPower: 0,
      magicResistance: 8,
      speed: 5,
      movementRange: 3,
      jumpHeight: 1,
      evasion: 0,
    },
    canFly: false,
    skillIdentifiers: ['rock_slam'],
    // Stone absorbs fire and earth; water erodes it.
    elementalAffinities: { fire: 0.25, earth: 0.5, water: 1.75 },
  },
  twisted_boar: {
    identifier: 'twisted_boar',
    displayName: 'Twisted Boar',
    level: 4,
    statistics: {
      hitPointsMaximum: 34,
      manaPointsMaximum: 6,
      attack: 11,
      defense: 6,
      magicPower: 0,
      magicResistance: 3,
      speed: 9,
      movementRange: 5,
      jumpHeight: 1,
      evasion: 0.05,
    },
    canFly: false,
    skillIdentifiers: ['goring_charge'],
    // Boars are tough but burn.
    elementalAffinities: { fire: 1.5, earth: 0.75 },
  },
  hollow_wisp: {
    identifier: 'hollow_wisp',
    displayName: 'Hollow Wisp',
    level: 4,
    statistics: {
      hitPointsMaximum: 18,
      manaPointsMaximum: 20,
      attack: 3,
      defense: 3,
      magicPower: 9,
      magicResistance: 8,
      speed: 8,
      movementRange: 4,
      jumpHeight: 2,
      evasion: 0.15,
    },
    canFly: true,
    skillIdentifiers: ['dark_bolt'],
    // A knot of the Darkness itself: Sacred burns it, Dark feeds it.
    elementalAffinities: { sacred: 1.5, dark: -1 },
  },
  gnarlroot: {
    identifier: 'gnarlroot',
    displayName: 'Gnarlroot',
    level: 3,
    statistics: {
      hitPointsMaximum: 34,
      manaPointsMaximum: 10,
      attack: 8,
      defense: 7,
      magicPower: 4,
      magicResistance: 6,
      speed: 6,
      movementRange: 3,
      jumpHeight: 1,
      evasion: 0.02,
    },
    canFly: false,
    skillIdentifiers: ['root_lash'],
    // Roots feed on water; fire scorches them; earth magic passes through.
    elementalAffinities: { fire: 1.75, water: 0.5, earth: 0.5 },
  },
};
