import type { SkillDefinition } from '../sim/battle/SkillDefinition';

/**
 * The shared skill pool (PRD §7): skills are defined once and referenced by
 * any class or monster that knows them.
 */
const SKILL_ENTRIES = {
  basic_attack: {
    identifier: 'basic_attack',
    displayName: 'Attack',
    description: 'A standard strike with the equipped weapon.',
    manaPointCost: 0,
    targetingRange: 1,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'physical', powerMultiplier: 1.0 },
  },

  // ── Warrior ────────────────────────────────────────────────────────────
  power_strike: {
    identifier: 'power_strike',
    displayName: 'Power Strike',
    description: 'A heavy two-handed blow dealing half again normal damage.',
    manaPointCost: 4,
    targetingRange: 1,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'physical', powerMultiplier: 1.5 },
  },
  war_cry: {
    identifier: 'war_cry',
    displayName: 'War Cry',
    description: 'A rallying roar that raises the user’s attack for three turns.',
    manaPointCost: 3,
    targetingRange: 0,
    areaOfEffectRadius: 0,
    targetTeam: 'self',
    effect: { kind: 'statModifier', statistic: 'attack', amount: 4, durationTurns: 3 },
  },

  // ── Thief ──────────────────────────────────────────────────────────────
  flanking_strike: {
    identifier: 'flanking_strike',
    displayName: 'Flanking Strike',
    description: 'A precise cut that punishes exposed sides and backs.',
    manaPointCost: 3,
    targetingRange: 1,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: {
      kind: 'damage',
      damageSource: 'physical',
      powerMultiplier: 1.1,
      flankingPowerBonus: 0.6,
    },
  },
  thrown_dagger: {
    identifier: 'thrown_dagger',
    displayName: 'Thrown Dagger',
    description: 'A dagger hurled at a target up to three tiles away.',
    manaPointCost: 2,
    targetingRange: 3,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'physical', powerMultiplier: 0.8 },
  },

  // ── Mage ───────────────────────────────────────────────────────────────
  fire_bolt: {
    identifier: 'fire_bolt',
    displayName: 'Fire Bolt',
    description: 'A searing bolt of Kosh’s element hurled at one target.',
    manaPointCost: 5,
    targetingRange: 4,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'magical', powerMultiplier: 1.4, element: 'fire' },
  },
  flame_burst: {
    identifier: 'flame_burst',
    displayName: 'Flame Burst',
    description: 'An eruption of fire that scorches the target tile and its surroundings.',
    manaPointCost: 8,
    targetingRange: 3,
    areaOfEffectRadius: 1,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'magical', powerMultiplier: 1.0, element: 'fire' },
  },

  // ── Thief (status) ────────────────────────────────────────────────────
  venom_strike: {
    identifier: 'venom_strike',
    displayName: 'Venom Strike',
    description: 'A blade coated in a fast-acting toxin. The wound festers for three turns.',
    manaPointCost: 4,
    targetingRange: 1,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'statusEffect', statusEffect: 'poison', durationTurns: 3 },
  },
  smoke_dart: {
    identifier: 'smoke_dart',
    displayName: 'Smoke Dart',
    description: "A blinding dart that clouds the target's vision for three turns.",
    manaPointCost: 4,
    targetingRange: 3,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'statusEffect', statusEffect: 'blind', durationTurns: 3 },
  },

  // ── Mage (status) ──────────────────────────────────────────────────────
  leaden_curse: {
    identifier: 'leaden_curse',
    displayName: 'Leaden Curse',
    description: 'A curse of leaden weight that drags at the target\'s every motion, slowing its turns.',
    manaPointCost: 6,
    targetingRange: 3,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'statusEffect', statusEffect: 'slow', durationTurns: 3 },
  },
  quickening: {
    identifier: 'quickening',
    displayName: 'Quickening',
    description: 'An incantation that quickens an ally\'s steps until the battle\'s rhythm bends around them.',
    manaPointCost: 8,
    targetingRange: 3,
    areaOfEffectRadius: 0,
    targetTeam: 'allies',
    effect: { kind: 'statusEffect', statusEffect: 'haste', durationTurns: 3 },
  },
  sleep_dust: {
    identifier: 'sleep_dust',
    displayName: 'Sleep Dust',
    description: 'A cloud of bewitched powder settles over one target, pulling them into a deep slumber.',
    manaPointCost: 7,
    targetingRange: 3,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'statusEffect', statusEffect: 'sleep', durationTurns: 2 },
  },

  // ── Warrior (earth) ────────────────────────────────────────────────────
  earth_spike: {
    identifier: 'earth_spike',
    displayName: 'Earth Spike',
    description: 'A fist driven into the ground calls up a spike of Taurk\'s stone beneath the target.',
    manaPointCost: 6,
    targetingRange: 2,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'physical', powerMultiplier: 1.3, element: 'earth' },
  },

  // ── Mage (water) ───────────────────────────────────────────────────────
  frost_bolt: {
    identifier: 'frost_bolt',
    displayName: 'Frost Bolt',
    description: 'A shard of Yiern\'s frozen breath, hurled with cutting precision.',
    manaPointCost: 5,
    targetingRange: 4,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'magical', powerMultiplier: 1.4, element: 'water' },
  },

  // ── Priest ─────────────────────────────────────────────────────────────
  first_aid: {
    identifier: 'first_aid',
    displayName: 'First Aid',
    description: 'A prayer of mending that restores an ally’s hit points.',
    manaPointCost: 4,
    targetingRange: 3,
    areaOfEffectRadius: 0,
    targetTeam: 'allies',
    effect: { kind: 'heal', powerMultiplier: 1.5 },
  },
  sacred_bolt: {
    identifier: 'sacred_bolt',
    displayName: 'Sacred Bolt',
    description: 'A lance of Hort’s light. Devastating against the unliving.',
    manaPointCost: 5,
    targetingRange: 3,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'magical', powerMultiplier: 1.2, element: 'sacred' },
  },

  // ── Spellthief (status) ────────────────────────────────────────────────
  mana_theft: {
    identifier: 'mana_theft',
    displayName: 'Mana Theft',
    description: 'A spellthief\'s touch that unravels the target\'s grip on their own magic, leaving only muscle and steel.',
    manaPointCost: 4,
    targetingRange: 3,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'statusEffect', statusEffect: 'silence', durationTurns: 3 },
  },

  // ── Necromancer (status) ───────────────────────────────────────────────
  grave_sentence: {
    identifier: 'grave_sentence',
    displayName: 'Grave Sentence',
    description: 'A curse of the unnamed god\'s own patience — a countdown the target can feel closing in.',
    manaPointCost: 8,
    targetingRange: 3,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'statusEffect', statusEffect: 'doom', durationTurns: 3 },
  },

  // ── Illusionist (status) ───────────────────────────────────────────────
  shattered_mind: {
    identifier: 'shattered_mind',
    displayName: 'Shattered Mind',
    description: 'A burst of false sight that turns the target against friend and foe alike.',
    manaPointCost: 6,
    targetingRange: 3,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'statusEffect', statusEffect: 'confuse', durationTurns: 2 },
  },

  // ── Berserker (status) ─────────────────────────────────────────────────
  feral_frenzy: {
    identifier: 'feral_frenzy',
    displayName: 'Feral Frenzy',
    description: 'The berserker gives up all restraint — every ounce of will turns to raw, unaimed violence.',
    manaPointCost: 5,
    targetingRange: 0,
    areaOfEffectRadius: 0,
    targetTeam: 'self',
    effect: { kind: 'statusEffect', statusEffect: 'berserk', durationTurns: 3 },
  },

  // ── Priest (wards) ─────────────────────────────────────────────────────
  mending_prayer: {
    identifier: 'mending_prayer',
    displayName: 'Mending Prayer',
    description: 'A sustained prayer of mending — the ally\'s wounds keep knitting closed at the start of each of their turns.',
    manaPointCost: 5,
    targetingRange: 3,
    areaOfEffectRadius: 0,
    targetTeam: 'allies',
    effect: { kind: 'statusEffect', statusEffect: 'regen', durationTurns: 3 },
  },
  ward_of_steel: {
    identifier: 'ward_of_steel',
    displayName: 'Ward of Steel',
    description: 'A ward against blade, claw, and tusk — physical blows lose much of their force.',
    manaPointCost: 5,
    targetingRange: 3,
    areaOfEffectRadius: 0,
    targetTeam: 'allies',
    effect: { kind: 'statusEffect', statusEffect: 'protect', durationTurns: 3 },
  },
  ward_of_faith: {
    identifier: 'ward_of_faith',
    displayName: 'Ward of Faith',
    description: 'A ward woven of faith that dampens hostile magic before it lands.',
    manaPointCost: 5,
    targetingRange: 3,
    areaOfEffectRadius: 0,
    targetTeam: 'allies',
    effect: { kind: 'statusEffect', statusEffect: 'shell', durationTurns: 3 },
  },

  // ── Equipment-bound (PRD §7 — granted by gear, mastered through use) ──
  cleaving_arc: {
    identifier: 'cleaving_arc',
    displayName: 'Cleaving Arc',
    description: 'A wide, tusk-heavy sweep that carries through everything beside the first target.',
    manaPointCost: 5,
    targetingRange: 1,
    areaOfEffectRadius: 1,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'physical', powerMultiplier: 1.1 },
  },
  shadow_fang: {
    identifier: 'shadow_fang',
    displayName: 'Shadow Fang',
    description: 'A werecat cut taught knife-to-hand: barely a scratch from the front, ruinous from behind.',
    manaPointCost: 4,
    targetingRange: 1,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: {
      kind: 'damage',
      damageSource: 'physical',
      powerMultiplier: 0.9,
      flankingPowerBonus: 0.9,
    },
  },
  tide_surge: {
    identifier: 'tide_surge',
    displayName: 'Tide Surge',
    description: 'Yiern\'s water called up as a single swell that breaks over the target and its neighbors.',
    manaPointCost: 8,
    targetingRange: 3,
    areaOfEffectRadius: 1,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'magical', powerMultiplier: 1.1, element: 'water' },
  },
  dawns_mercy: {
    identifier: 'dawns_mercy',
    displayName: 'Dawn\'s Mercy',
    description: 'A Hortian prayer of first light that mends every ally standing close together.',
    manaPointCost: 8,
    targetingRange: 3,
    areaOfEffectRadius: 1,
    targetTeam: 'allies',
    effect: { kind: 'heal', powerMultiplier: 1.2 },
  },

  // ── Creatures of the Darkness ──────────────────────────────────────────
  savage_bite: {
    identifier: 'savage_bite',
    displayName: 'Savage Bite',
    description: 'Twisted fangs tear at the target.',
    manaPointCost: 2,
    targetingRange: 1,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'physical', powerMultiplier: 1.25 },
  },
  rock_slam: {
    identifier: 'rock_slam',
    displayName: 'Rock Slam',
    description: 'A living boulder brings its whole mass down on the target.',
    manaPointCost: 3,
    targetingRange: 1,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'physical', powerMultiplier: 1.5 },
  },
  root_lash: {
    identifier: 'root_lash',
    displayName: 'Root Lash',
    description: 'A gnarled root whips out at a target two tiles away.',
    manaPointCost: 2,
    targetingRange: 2,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'physical', powerMultiplier: 1.1, element: 'earth' },
  },
  goring_charge: {
    identifier: 'goring_charge',
    displayName: 'Goring Charge',
    description: 'Twisted tusks slam home with the boar’s full weight behind them.',
    manaPointCost: 3,
    targetingRange: 1,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'physical', powerMultiplier: 1.4 },
  },
  dark_bolt: {
    identifier: 'dark_bolt',
    displayName: 'Dark Bolt',
    description: 'A mote of the unnamed god’s element, flung cold and silent.',
    manaPointCost: 4,
    targetingRange: 3,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'magical', powerMultiplier: 1.2, element: 'dark' },
  },
  petrifying_gaze: {
    identifier: 'petrifying_gaze',
    displayName: 'Petrifying Gaze',
    description: 'A stoneling\'s stare locks its target still as the rock it\'s made of.',
    manaPointCost: 4,
    targetingRange: 2,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'statusEffect', statusEffect: 'stop', durationTurns: 2 },
  },
  drowse_spores: {
    identifier: 'drowse_spores',
    displayName: 'Drowse Spores',
    description: 'A puff of blue flower-dust from the bloom’s maw — Slumber Meadow’s namesake, weaponized.',
    manaPointCost: 6,
    targetingRange: 2,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'statusEffect', statusEffect: 'sleep', durationTurns: 2 },
  },
  jagged_shiv: {
    identifier: 'jagged_shiv',
    displayName: 'Jagged Shiv',
    description: 'A rusted blade jabbed in fast, mean, and low.',
    manaPointCost: 2,
    targetingRange: 1,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'physical', powerMultiplier: 1.2 },
  },
  crushing_blow: {
    identifier: 'crushing_blow',
    displayName: 'Crushing Blow',
    description: 'A club the size of a fence post, swung with an orc’s full shoulders.',
    manaPointCost: 3,
    targetingRange: 1,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'physical', powerMultiplier: 1.5 },
  },
  horn_toss: {
    identifier: 'horn_toss',
    displayName: 'Horn Toss',
    description: 'The minotaur hooks its horns under the target and heaves.',
    manaPointCost: 3,
    targetingRange: 1,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'physical', powerMultiplier: 1.5 },
  },
  talon_dive: {
    identifier: 'talon_dive',
    displayName: 'Talon Dive',
    description: 'A silent stoop out of the canopy, talons first.',
    manaPointCost: 2,
    targetingRange: 1,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'physical', powerMultiplier: 1.3 },
  },
  gale_burst: {
    identifier: 'gale_burst',
    displayName: 'Gale Burst',
    description: 'A hard knot of Breir’s wind, loosed all at once.',
    manaPointCost: 4,
    targetingRange: 3,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'magical', powerMultiplier: 1.2, element: 'wind' },
  },
  bough_smash: {
    identifier: 'bough_smash',
    displayName: 'Bough Smash',
    description: 'A limb thick as a roof beam comes down like one.',
    manaPointCost: 3,
    targetingRange: 1,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'physical', powerMultiplier: 1.5, element: 'earth' },
  },

  // ── Skylancer (advanced class) ────────────────────────────────────
  skyfall_strike: {
    identifier: 'skyfall_strike',
    displayName: 'Skyfall Strike',
    description: 'A dive that only counts the moment steel meets ground.',
    manaPointCost: 5,
    targetingRange: 1,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'physical', powerMultiplier: 1.7 },
  },
  wingbeat_barrage: {
    identifier: 'wingbeat_barrage',
    displayName: 'Wingbeat Barrage',
    description: "The dive doesn't stop at one target — wings scatter everyone at the point of impact.",
    manaPointCost: 7,
    targetingRange: 1,
    areaOfEffectRadius: 1,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'physical', powerMultiplier: 1.2 },
  },
  zenith_dive: {
    identifier: 'zenith_dive',
    displayName: 'Zenith Dive',
    description: 'The full height of the sky, brought down on one point.',
    manaPointCost: 8,
    targetingRange: 1,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'physical', powerMultiplier: 2 },
  },

  // ── Spellblade (advanced class) ────────────────────────────────────
  stormforged_edge: {
    identifier: 'stormforged_edge',
    displayName: 'Stormforged Edge',
    description: 'The godless element, forced into the blade mid-swing.',
    manaPointCost: 6,
    targetingRange: 1,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'physical', powerMultiplier: 1.3, element: 'lightning' },
  },
  thunderclap_slash: {
    identifier: 'thunderclap_slash',
    displayName: 'Thunderclap Slash',
    description: "The storm doesn't wait for a second swing.",
    manaPointCost: 7,
    targetingRange: 1,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'physical', powerMultiplier: 1.5, element: 'lightning', flankingPowerBonus: 0.3 },
  },
  godless_current: {
    identifier: 'godless_current',
    displayName: 'Godless Current',
    description: 'Even a people who renounced every god still get struck by lightning.',
    manaPointCost: 9,
    targetingRange: 3,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'magical', powerMultiplier: 1.6, element: 'lightning' },
  },

  // ── Skytalon (advanced class) ────────────────────────────────────
  talon_rake: {
    identifier: 'talon_rake',
    displayName: 'Talon Rake',
    description: "A stoop from altitude that punishes anyone who can't keep their guard raised.",
    manaPointCost: 4,
    targetingRange: 1,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'physical', powerMultiplier: 1.2, flankingPowerBonus: 0.5 },
  },
  wingclip: {
    identifier: 'wingclip',
    displayName: 'Wingclip',
    description: 'Clip the wings, and even the fastest prey slows to a walk.',
    manaPointCost: 5,
    targetingRange: 2,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'statusEffect', statusEffect: 'slow', durationTurns: 3 },
  },
  apex_predator: {
    identifier: 'apex_predator',
    displayName: 'Apex Predator',
    description: 'No target has ever out-flown this.',
    manaPointCost: 7,
    targetingRange: 1,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'physical', powerMultiplier: 1.6, flankingPowerBonus: 0.8 },
  },

  // ── Dragoon (advanced class) ────────────────────────────────────
  dragoons_descent: {
    identifier: 'dragoons_descent',
    displayName: "Dragoon's Descent",
    description: 'A leap that lands with the whole fall behind it.',
    manaPointCost: 5,
    targetingRange: 1,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'physical', powerMultiplier: 1.6 },
  },
  lance_sweep: {
    identifier: 'lance_sweep',
    displayName: 'Lance Sweep',
    description: "The lance doesn't discriminate between the target and whoever's standing next to them.",
    manaPointCost: 6,
    targetingRange: 1,
    areaOfEffectRadius: 1,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'physical', powerMultiplier: 1.2 },
  },
  heavens_judgment: {
    identifier: 'heavens_judgment',
    displayName: "Heaven's Judgment",
    description: 'There is no guard for a blow that fell from that high.',
    manaPointCost: 9,
    targetingRange: 1,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'physical', powerMultiplier: 2.1 },
  },

  // ── Black Mage (advanced class) ────────────────────────────────────
  cataclysm: {
    identifier: 'cataclysm',
    displayName: 'Cataclysm',
    description: 'Unaimed, indiscriminate ruin — the price of power this raw.',
    manaPointCost: 10,
    targetingRange: 3,
    areaOfEffectRadius: 1,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'magical', powerMultiplier: 1.3 },
  },
  ruinbolt: {
    identifier: 'ruinbolt',
    displayName: 'Ruinbolt',
    description: "Precision isn't the point. Power is.",
    manaPointCost: 7,
    targetingRange: 4,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'magical', powerMultiplier: 1.5 },
  },
  annihilate: {
    identifier: 'annihilate',
    displayName: 'Annihilate',
    description: 'The single most destructive thing a Human can learn to cast.',
    manaPointCost: 12,
    targetingRange: 4,
    areaOfEffectRadius: 1,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'magical', powerMultiplier: 1.6 },
  },

  // ── Bishop (advanced class) ────────────────────────────────────
  zealous_rite: {
    identifier: 'zealous_rite',
    displayName: 'Zealous Rite',
    description: "Hort's mercy, poured over everyone still standing nearby.",
    manaPointCost: 9,
    targetingRange: 3,
    areaOfEffectRadius: 1,
    targetTeam: 'allies',
    effect: { kind: 'heal', powerMultiplier: 1.3 },
  },
  horts_rebuke: {
    identifier: 'horts_rebuke',
    displayName: "Hort's Rebuke",
    description: "Mercy for the faithful; judgment for what isn't.",
    manaPointCost: 6,
    targetingRange: 3,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'magical', powerMultiplier: 1.3, element: 'sacred' },
  },
  grand_benediction: {
    identifier: 'grand_benediction',
    displayName: 'Grand Benediction',
    description: "When Hort's mercy is needed most, this is what a Bishop trained for.",
    manaPointCost: 11,
    targetingRange: 3,
    areaOfEffectRadius: 1,
    targetTeam: 'allies',
    effect: { kind: 'heal', powerMultiplier: 1.6 },
  },

  // ── Paladin (advanced class) ────────────────────────────────────
  guardians_oath: {
    identifier: 'guardians_oath',
    displayName: "Guardian's Oath",
    description: 'A vow spoken mid-battle that dulls every blow that follows.',
    manaPointCost: 4,
    targetingRange: 0,
    areaOfEffectRadius: 0,
    targetTeam: 'self',
    effect: { kind: 'statModifier', statistic: 'defense', amount: 4, durationTurns: 3 },
  },
  smite_the_unholy: {
    identifier: 'smite_the_unholy',
    displayName: 'Smite the Unholy',
    description: 'A blade blessed twice over — once by Hort, once by every ally behind it.',
    manaPointCost: 6,
    targetingRange: 1,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'physical', powerMultiplier: 1.4, element: 'sacred' },
  },
  aegis_of_hort: {
    identifier: 'aegis_of_hort',
    displayName: 'Aegis of Hort',
    description: "The Paladin's oath was never just to themselves.",
    manaPointCost: 7,
    targetingRange: 3,
    areaOfEffectRadius: 0,
    targetTeam: 'allies',
    effect: { kind: 'statusEffect', statusEffect: 'protect', durationTurns: 3 },
  },

  // ── Rune Knight (advanced class) ────────────────────────────────────
  rune_of_power: {
    identifier: 'rune_of_power',
    displayName: 'Rune of Power',
    description: 'A sigil flares along the blade — arcane weight behind the next several swings.',
    manaPointCost: 4,
    targetingRange: 0,
    areaOfEffectRadius: 0,
    targetTeam: 'self',
    effect: { kind: 'statModifier', statistic: 'magicPower', amount: 4, durationTurns: 3 },
  },
  runic_strike: {
    identifier: 'runic_strike',
    displayName: 'Runic Strike',
    description: "The rune doesn't glow until the moment it lands.",
    manaPointCost: 6,
    targetingRange: 1,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'physical', powerMultiplier: 1.5 },
  },
  grand_etching: {
    identifier: 'grand_etching',
    displayName: 'Grand Etching',
    description: 'Every rune the Knight has ever learned, carved into one blade at once.',
    manaPointCost: 7,
    targetingRange: 0,
    areaOfEffectRadius: 0,
    targetTeam: 'self',
    effect: { kind: 'statModifier', statistic: 'magicPower', amount: 7, durationTurns: 4 },
  },

  // ── Inquisitor (advanced class) ────────────────────────────────────
  zealots_judgment: {
    identifier: 'zealots_judgment',
    displayName: "Zealot's Judgment",
    description: 'Faith made into a blade-edge — merciless against anything the Darkness has touched.',
    manaPointCost: 5,
    targetingRange: 1,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'physical', powerMultiplier: 1.3, element: 'sacred' },
  },
  binding_oath: {
    identifier: 'binding_oath',
    displayName: 'Binding Oath',
    description: 'Whatever the Darkness gave it to cast, the Inquisitor takes back first.',
    manaPointCost: 5,
    targetingRange: 3,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'statusEffect', statusEffect: 'silence', durationTurns: 3 },
  },
  final_verdict: {
    identifier: 'final_verdict',
    displayName: 'Final Verdict',
    description: 'The last word an Inquisitor ever needs to have.',
    manaPointCost: 8,
    targetingRange: 1,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'physical', powerMultiplier: 1.7, element: 'sacred' },
  },

  // ── Illusionist (advanced class) ────────────────────────────────────
  veil_of_lies: {
    identifier: 'veil_of_lies',
    displayName: 'Veil of Lies',
    description: 'The mind sees exactly what the Illusionist wants it to.',
    manaPointCost: 5,
    targetingRange: 3,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'statusEffect', statusEffect: 'blind', durationTurns: 3 },
  },
  waking_nightmare: {
    identifier: 'waking_nightmare',
    displayName: 'Waking Nightmare',
    description: 'Every enemy in the blast sees something different, and none of it is real.',
    manaPointCost: 9,
    targetingRange: 3,
    areaOfEffectRadius: 1,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'magical', powerMultiplier: 1.3 },
  },

  // ── Spellthief (advanced class) ────────────────────────────────────
  arcane_pilfer: {
    identifier: 'arcane_pilfer',
    displayName: 'Arcane Pilfer',
    description: "Whatever this doesn't kill, it leaves poorer.",
    manaPointCost: 5,
    targetingRange: 3,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'magical', powerMultiplier: 1.2 },
  },
  grand_larceny: {
    identifier: 'grand_larceny',
    displayName: 'Grand Larceny',
    description: "A whole line of casters, suddenly reaching for spells that aren't there.",
    manaPointCost: 9,
    targetingRange: 3,
    areaOfEffectRadius: 1,
    targetTeam: 'enemies',
    effect: { kind: 'statusEffect', statusEffect: 'silence', durationTurns: 3 },
  },

  // ── Dread Knight (advanced class) ────────────────────────────────────
  grim_resolve: {
    identifier: 'grim_resolve',
    displayName: 'Grim Resolve',
    description: "The wound doesn't stop them. It never did. It just feeds the next swing.",
    manaPointCost: 4,
    targetingRange: 0,
    areaOfEffectRadius: 0,
    targetTeam: 'self',
    effect: { kind: 'statModifier', statistic: 'attack', amount: 5, durationTurns: 3 },
  },
  undying_blow: {
    identifier: 'undying_blow',
    displayName: 'Undying Blow',
    description: 'It hits like something that has nothing left to lose.',
    manaPointCost: 6,
    targetingRange: 1,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'physical', powerMultiplier: 1.6 },
  },
  wrath_undying: {
    identifier: 'wrath_undying',
    displayName: 'Wrath Undying',
    description: 'The Darkness made them this way. This is what it gets back.',
    manaPointCost: 8,
    targetingRange: 1,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'physical', powerMultiplier: 1.8, element: 'dark' },
  },

  // ── Pyromancer (advanced class) ────────────────────────────────────
  infernal_pyre: {
    identifier: 'infernal_pyre',
    displayName: 'Infernal Pyre',
    description: "Kosh's fire, called down without mercy for the god who lets them keep fighting.",
    manaPointCost: 9,
    targetingRange: 3,
    areaOfEffectRadius: 1,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'magical', powerMultiplier: 1.4, element: 'fire' },
  },
  koshs_wrath: {
    identifier: 'koshs_wrath',
    displayName: "Kosh's Wrath",
    description: "The god of fire doesn't do subtlety, and neither do they.",
    manaPointCost: 7,
    targetingRange: 4,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'magical', powerMultiplier: 1.6, element: 'fire' },
  },
  immolation: {
    identifier: 'immolation',
    displayName: 'Immolation',
    description: 'Everything the pyre touches, it keeps.',
    manaPointCost: 11,
    targetingRange: 4,
    areaOfEffectRadius: 1,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'magical', powerMultiplier: 1.5, element: 'fire' },
  },

  // ── Revenant (advanced class) ────────────────────────────────────
  undying_assault: {
    identifier: 'undying_assault',
    displayName: 'Undying Assault',
    description: "An attack that doesn't care it's already been struck down once tonight.",
    manaPointCost: 5,
    targetingRange: 1,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'physical', powerMultiplier: 1.5, flankingPowerBonus: 0.4 },
  },
  grave_momentum: {
    identifier: 'grave_momentum',
    displayName: 'Grave Momentum',
    description: 'Being knocked down just means the next swing starts lower.',
    manaPointCost: 5,
    targetingRange: 1,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'physical', powerMultiplier: 1.4, flankingPowerBonus: 0.5 },
  },
  refuse_to_fall: {
    identifier: 'refuse_to_fall',
    displayName: 'Refuse to Fall',
    description: 'There is no version of this fight where the Revenant simply stops.',
    manaPointCost: 6,
    targetingRange: 0,
    areaOfEffectRadius: 0,
    targetTeam: 'self',
    effect: { kind: 'statModifier', statistic: 'attack', amount: 7, durationTurns: 3 },
  },

  // ── Ashguard (advanced class) ────────────────────────────────────
  cinderward: {
    identifier: 'cinderward',
    displayName: 'Cinderward',
    description: 'Fire-hardened skin turned ward — nothing sticks that would fell the living.',
    manaPointCost: 5,
    targetingRange: 0,
    areaOfEffectRadius: 0,
    targetTeam: 'self',
    effect: { kind: 'statusEffect', statusEffect: 'protect', durationTurns: 3 },
  },
  ash_hardened_blow: {
    identifier: 'ash_hardened_blow',
    displayName: 'Ash-Hardened Blow',
    description: 'Skin like a dying coal — and a fist to match.',
    manaPointCost: 6,
    targetingRange: 1,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'physical', powerMultiplier: 1.4, element: 'fire' },
  },
  unyielding_ember: {
    identifier: 'unyielding_ember',
    displayName: 'Unyielding Ember',
    description: 'Nothing has stuck to an Ashguard yet.',
    manaPointCost: 6,
    targetingRange: 0,
    areaOfEffectRadius: 0,
    targetTeam: 'self',
    effect: { kind: 'statusEffect', statusEffect: 'protect', durationTurns: 4 },
  },

  // ── Wraith (advanced class) ────────────────────────────────────
  shadow_rend: {
    identifier: 'shadow_rend',
    displayName: 'Shadow Rend',
    description: 'The darkness they despise, turned into a blade only they can wield.',
    manaPointCost: 6,
    targetingRange: 3,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'magical', powerMultiplier: 1.3, element: 'dark' },
  },
  grasping_shadow: {
    identifier: 'grasping_shadow',
    displayName: 'Grasping Shadow',
    description: 'The dark reaches out, and whatever it touches slows to nothing.',
    manaPointCost: 5,
    targetingRange: 3,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'statusEffect', statusEffect: 'slow', durationTurns: 3 },
  },
  voidrend: {
    identifier: 'voidrend',
    displayName: 'Voidrend',
    description: 'Turning the thing they hate most into the last thing an enemy sees.',
    manaPointCost: 8,
    targetingRange: 4,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'magical', powerMultiplier: 1.6, element: 'dark' },
  },

  // ── Necromancer (advanced class) ────────────────────────────────────
  bone_lance: {
    identifier: 'bone_lance',
    displayName: 'Bone Lance',
    description: 'A shard of grave-dust given a killing edge.',
    manaPointCost: 6,
    targetingRange: 4,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'magical', powerMultiplier: 1.4, element: 'dark' },
  },
  reapers_toll: {
    identifier: 'reapers_toll',
    displayName: "Reaper's Toll",
    description: "Death doesn't ask twice at this range.",
    manaPointCost: 10,
    targetingRange: 3,
    areaOfEffectRadius: 1,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'magical', powerMultiplier: 1.3, element: 'dark' },
  },

  // ── Shadowdancer (advanced class) ────────────────────────────────────
  umbral_step: {
    identifier: 'umbral_step',
    displayName: 'Umbral Step',
    description: 'A blink through shadow-glare — gone before the counter lands.',
    manaPointCost: 4,
    targetingRange: 0,
    areaOfEffectRadius: 0,
    targetTeam: 'self',
    effect: { kind: 'statModifier', statistic: 'speed', amount: 4, durationTurns: 3 },
  },
  vanishing_cut: {
    identifier: 'vanishing_cut',
    displayName: 'Vanishing Cut',
    description: 'Gone before the blade even finishes its arc.',
    manaPointCost: 5,
    targetingRange: 1,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'physical', powerMultiplier: 1.3, flankingPowerBonus: 0.6 },
  },
  shadows_grace: {
    identifier: 'shadows_grace',
    displayName: "Shadow's Grace",
    description: "At this speed, being hit isn't really an option anymore.",
    manaPointCost: 7,
    targetingRange: 0,
    areaOfEffectRadius: 0,
    targetTeam: 'self',
    effect: { kind: 'statModifier', statistic: 'speed', amount: 7, durationTurns: 4 },
  },

  // ── Galeweaver (advanced class) ────────────────────────────────────
  cutting_gale: {
    identifier: 'cutting_gale',
    displayName: 'Cutting Gale',
    description: "Breir's wind, sharpened to a blade's edge.",
    manaPointCost: 5,
    targetingRange: 4,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'magical', powerMultiplier: 1.4, element: 'wind' },
  },
  windward_ward: {
    identifier: 'windward_ward',
    displayName: 'Windward Ward',
    description: "Breir's wind doesn't just cut. It carries, too.",
    manaPointCost: 6,
    targetingRange: 3,
    areaOfEffectRadius: 0,
    targetTeam: 'allies',
    effect: { kind: 'statusEffect', statusEffect: 'haste', durationTurns: 3 },
  },
  cyclone: {
    identifier: 'cyclone',
    displayName: 'Cyclone',
    description: 'A gale big enough that nothing near the eye of it stays standing.',
    manaPointCost: 10,
    targetingRange: 4,
    areaOfEffectRadius: 1,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'magical', powerMultiplier: 1.4, element: 'wind' },
  },

  // ── Windwanderer (advanced class) ────────────────────────────────────
  gale_step_strike: {
    identifier: 'gale_step_strike',
    displayName: 'Gale-Step Strike',
    description: "Breir's wind wound tight around every step, loosed on impact.",
    manaPointCost: 5,
    targetingRange: 1,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'physical', powerMultiplier: 1.3, element: 'wind' },
  },
  tempest_step: {
    identifier: 'tempest_step',
    displayName: 'Tempest Step',
    description: 'As fast as the gale they emulate — difficult to hit, impossible to outrun.',
    manaPointCost: 5,
    targetingRange: 0,
    areaOfEffectRadius: 0,
    targetTeam: 'self',
    effect: { kind: 'statModifier', statistic: 'speed', amount: 5, durationTurns: 3 },
  },
  breirs_fury: {
    identifier: 'breirs_fury',
    displayName: "Breir's Fury",
    description: "Every step of wind they've gathered, spent in a single strike.",
    manaPointCost: 8,
    targetingRange: 1,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'physical', powerMultiplier: 1.7, element: 'wind' },
  },

  // ── Priest of the 8 Lives (advanced class) ────────────────────────────────────
  eighth_lifes_vow: {
    identifier: 'eighth_lifes_vow',
    displayName: "Eighth Life's Vow",
    description: 'One life already spent on the shrines — this one, they intend to keep.',
    manaPointCost: 5,
    targetingRange: 0,
    areaOfEffectRadius: 0,
    targetTeam: 'self',
    effect: { kind: 'statusEffect', statusEffect: 'regen', durationTurns: 3 },
  },
  windward_blow: {
    identifier: 'windward_blow',
    displayName: 'Windward Blow',
    description: 'Wind in the step, earth in the swing.',
    manaPointCost: 5,
    targetingRange: 1,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'physical', powerMultiplier: 1.3, element: 'wind' },
  },
  shrine_blessed: {
    identifier: 'shrine_blessed',
    displayName: 'Shrine-Blessed',
    description: 'The swiftness they carry into every fight, lent to whoever fights beside them.',
    manaPointCost: 7,
    targetingRange: 3,
    areaOfEffectRadius: 0,
    targetTeam: 'allies',
    effect: { kind: 'statusEffect', statusEffect: 'haste', durationTurns: 3 },
  },

  // ── Phantom (advanced class) ────────────────────────────────────
  phantom_step: {
    identifier: 'phantom_step',
    displayName: 'Phantom Step',
    description: "They see three of you. They can't tell which one swung.",
    manaPointCost: 4,
    targetingRange: 1,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'physical', powerMultiplier: 1.1, flankingPowerBonus: 0.7 },
  },
  after_image: {
    identifier: 'after_image',
    displayName: 'After-Image',
    description: "Three of you, and the enemy's blade always picks wrong.",
    manaPointCost: 5,
    targetingRange: 0,
    areaOfEffectRadius: 0,
    targetTeam: 'self',
    effect: { kind: 'statModifier', statistic: 'defense', amount: 5, durationTurns: 3 },
  },
  vanishing_flurry: {
    identifier: 'vanishing_flurry',
    displayName: 'Vanishing Flurry',
    description: 'By the time the first cut registers, the Phantom is already three strikes ahead.',
    manaPointCost: 7,
    targetingRange: 1,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'physical', powerMultiplier: 1.3, flankingPowerBonus: 0.9 },
  },

  // ── Shrine Warden (advanced class) ────────────────────────────────────
  wardens_blessing: {
    identifier: 'wardens_blessing',
    displayName: "Warden's Blessing",
    description: 'A blessing drawn from the shrines, laid over an ally like a second skin.',
    manaPointCost: 5,
    targetingRange: 3,
    areaOfEffectRadius: 0,
    targetTeam: 'allies',
    effect: { kind: 'statusEffect', statusEffect: 'protect', durationTurns: 3 },
  },
  taurks_rebuke: {
    identifier: 'taurks_rebuke',
    displayName: "Taurk's Rebuke",
    description: 'Even a guardian has to fight sometimes.',
    manaPointCost: 5,
    targetingRange: 1,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'physical', powerMultiplier: 1.3, element: 'earth' },
  },
  twin_shrine_ward: {
    identifier: 'twin_shrine_ward',
    displayName: 'Twin Shrine Ward',
    description: 'Wind against blades, earth against magic — the shrines give both.',
    manaPointCost: 6,
    targetingRange: 3,
    areaOfEffectRadius: 0,
    targetTeam: 'allies',
    effect: { kind: 'statusEffect', statusEffect: 'shell', durationTurns: 3 },
  },

  // ── Geomancer (advanced class) ────────────────────────────────────
  stone_fang: {
    identifier: 'stone_fang',
    displayName: 'Stone Fang',
    description: "The ground itself bites when Taurk's earth answers the call.",
    manaPointCost: 5,
    targetingRange: 4,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'magical', powerMultiplier: 1.4, element: 'earth' },
  },
  quaking_ground: {
    identifier: 'quaking_ground',
    displayName: 'Quaking Ground',
    description: "The ground doesn't ask who's standing on it.",
    manaPointCost: 7,
    targetingRange: 3,
    areaOfEffectRadius: 1,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'magical', powerMultiplier: 1.2, element: 'earth' },
  },
  taurks_judgment: {
    identifier: 'taurks_judgment',
    displayName: "Taurk's Judgment",
    description: "When Taurk answers personally, the earth doesn't do anything by half measures.",
    manaPointCost: 9,
    targetingRange: 4,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'magical', powerMultiplier: 1.7, element: 'earth' },
  },

  // ── Shaman (advanced class) ────────────────────────────────────
  tidal_blessing: {
    identifier: 'tidal_blessing',
    displayName: 'Tidal Blessing',
    description: "Yiern's water, poured out over everyone still on their feet nearby.",
    manaPointCost: 8,
    targetingRange: 3,
    areaOfEffectRadius: 1,
    targetTeam: 'allies',
    effect: { kind: 'heal', powerMultiplier: 1.3 },
  },
  yierns_ward: {
    identifier: 'yierns_ward',
    displayName: "Yiern's Ward",
    description: 'The tide always comes back — so do the wounds it keeps mending.',
    manaPointCost: 5,
    targetingRange: 3,
    areaOfEffectRadius: 0,
    targetTeam: 'allies',
    effect: { kind: 'statusEffect', statusEffect: 'regen', durationTurns: 3 },
  },
  deep_renewal: {
    identifier: 'deep_renewal',
    displayName: 'Deep Renewal',
    description: "Water finds every crack — even the ones that shouldn't still be open.",
    manaPointCost: 8,
    targetingRange: 3,
    areaOfEffectRadius: 0,
    targetTeam: 'allies',
    effect: { kind: 'heal', powerMultiplier: 1.8 },
  },

  // ── Stonefist (advanced class) ────────────────────────────────────
  earthen_fist: {
    identifier: 'earthen_fist',
    displayName: 'Earthen Fist',
    description: 'A blow that lands like the quarry face giving way.',
    manaPointCost: 6,
    targetingRange: 1,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'physical', powerMultiplier: 1.5, element: 'earth' },
  },
  quarry_breaker: {
    identifier: 'quarry_breaker',
    displayName: 'Quarry Breaker',
    description: 'One fist, and the ground around the target agrees to move too.',
    manaPointCost: 7,
    targetingRange: 1,
    areaOfEffectRadius: 1,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'physical', powerMultiplier: 1.3, element: 'earth' },
  },
  mountains_weight: {
    identifier: 'mountains_weight',
    displayName: "Mountain's Weight",
    description: 'What Stonefists lack in speed, this makes up for entirely.',
    manaPointCost: 8,
    targetingRange: 1,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'physical', powerMultiplier: 1.8, element: 'earth' },
  },

  // ── Totem Guard (advanced class) ────────────────────────────────────
  totem_of_resilience: {
    identifier: 'totem_of_resilience',
    displayName: 'Totem of Resilience',
    description: "A totem struck into the ground — the earth's stubbornness, shared with everyone nearby.",
    manaPointCost: 5,
    targetingRange: 3,
    areaOfEffectRadius: 0,
    targetTeam: 'allies',
    effect: { kind: 'statusEffect', statusEffect: 'regen', durationTurns: 3 },
  },
  guardian_totem: {
    identifier: 'guardian_totem',
    displayName: 'Guardian Totem',
    description: 'A second totem, a second promise — the line holds a little longer.',
    manaPointCost: 5,
    targetingRange: 3,
    areaOfEffectRadius: 0,
    targetTeam: 'allies',
    effect: { kind: 'statusEffect', statusEffect: 'protect', durationTurns: 3 },
  },
  ancestors_stand: {
    identifier: 'ancestors_stand',
    displayName: "Ancestor's Stand",
    description: "Every totem they've ever raised, standing behind this one soldier now.",
    manaPointCost: 6,
    targetingRange: 0,
    areaOfEffectRadius: 0,
    targetTeam: 'self',
    effect: { kind: 'statModifier', statistic: 'defense', amount: 6, durationTurns: 4 },
  },

  // ── Knight (advanced class) ────────────────────────────────────
  bulwark_stance: {
    identifier: 'bulwark_stance',
    displayName: 'Bulwark Stance',
    description: 'Plant your feet. The line does not move.',
    manaPointCost: 4,
    targetingRange: 0,
    areaOfEffectRadius: 0,
    targetTeam: 'self',
    effect: { kind: 'statModifier', statistic: 'defense', amount: 6, durationTurns: 3 },
  },
  shield_wall: {
    identifier: 'shield_wall',
    displayName: 'Shield Wall',
    description: 'The Knight was never just protecting themselves.',
    manaPointCost: 5,
    targetingRange: 3,
    areaOfEffectRadius: 0,
    targetTeam: 'allies',
    effect: { kind: 'statusEffect', statusEffect: 'protect', durationTurns: 3 },
  },
  immovable: {
    identifier: 'immovable',
    displayName: 'Immovable',
    description: 'Something this stubborn was never going anywhere.',
    manaPointCost: 7,
    targetingRange: 0,
    areaOfEffectRadius: 0,
    targetTeam: 'self',
    effect: { kind: 'statModifier', statistic: 'defense', amount: 9, durationTurns: 4 },
  },

  // ── Ranger (advanced class) ────────────────────────────────────
  longshot: {
    identifier: 'longshot',
    displayName: 'Longshot',
    description: "Already gone before the bowstring's hum fades.",
    manaPointCost: 5,
    targetingRange: 4,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'physical', powerMultiplier: 1.3 },
  },
  pinning_shot: {
    identifier: 'pinning_shot',
    displayName: 'Pinning Shot',
    description: "An arrow doesn't have to kill to end a fight — it just has to stop the legs.",
    manaPointCost: 5,
    targetingRange: 4,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'statusEffect', statusEffect: 'slow', durationTurns: 3 },
  },
  dead_aim: {
    identifier: 'dead_aim',
    displayName: 'Dead Aim',
    description: "By the time anything closes that distance, it's already too late.",
    manaPointCost: 7,
    targetingRange: 5,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'physical', powerMultiplier: 1.6 },
  },

  // ── Duelist (advanced class) ────────────────────────────────────
  riposte_cut: {
    identifier: 'riposte_cut',
    displayName: 'Riposte Cut',
    description: 'Every opening you show, the duelist has already used against you.',
    manaPointCost: 4,
    targetingRange: 1,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'physical', powerMultiplier: 1.4, flankingPowerBonus: 0.3 },
  },
  feinting_blade: {
    identifier: 'feinting_blade',
    displayName: 'Feinting Blade',
    description: "Reading the opponent's next move is half the fight — the Duelist has already won that half.",
    manaPointCost: 4,
    targetingRange: 0,
    areaOfEffectRadius: 0,
    targetTeam: 'self',
    effect: { kind: 'statModifier', statistic: 'defense', amount: 4, durationTurns: 3 },
  },
  perfect_counter: {
    identifier: 'perfect_counter',
    displayName: 'Perfect Counter',
    description: 'No opening left. No hit that lands clean anymore.',
    manaPointCost: 6,
    targetingRange: 1,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'physical', powerMultiplier: 1.5, flankingPowerBonus: 0.6 },
  },

  // ── Sage (advanced class) ────────────────────────────────────
  arcane_ward: {
    identifier: 'arcane_ward',
    displayName: 'Arcane Ward',
    description: "A scholar's ward, half prayer and half formula, laid over an ally's mind.",
    manaPointCost: 5,
    targetingRange: 3,
    areaOfEffectRadius: 0,
    targetTeam: 'allies',
    effect: { kind: 'statusEffect', statusEffect: 'shell', durationTurns: 3 },
  },
  scholars_cure: {
    identifier: 'scholars_cure',
    displayName: "Scholar's Cure",
    description: "Half the Priest's gift, all of the effort.",
    manaPointCost: 6,
    targetingRange: 3,
    areaOfEffectRadius: 0,
    targetTeam: 'allies',
    effect: { kind: 'heal', powerMultiplier: 1.4 },
  },
  twin_study: {
    identifier: 'twin_study',
    displayName: 'Twin Study',
    description: 'What the Mage would call basic, the Sage calls Tuesday.',
    manaPointCost: 8,
    targetingRange: 4,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'magical', powerMultiplier: 1.4 },
  },

  // ── Assassin (advanced class) ────────────────────────────────────
  killing_blow: {
    identifier: 'killing_blow',
    displayName: 'Killing Blow',
    description: "A strike meant to end the fight before it's had time to start.",
    manaPointCost: 6,
    targetingRange: 1,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'physical', powerMultiplier: 1.7 },
  },
  silent_approach: {
    identifier: 'silent_approach',
    displayName: 'Silent Approach',
    description: 'No target ever hears the Assassin coming twice.',
    manaPointCost: 4,
    targetingRange: 0,
    areaOfEffectRadius: 0,
    targetTeam: 'self',
    effect: { kind: 'statModifier', statistic: 'speed', amount: 5, durationTurns: 3 },
  },
  no_target_is_safe: {
    identifier: 'no_target_is_safe',
    displayName: 'No Target Is Safe',
    description: "The class's whole promise, delivered in one motion.",
    manaPointCost: 9,
    targetingRange: 1,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'physical', powerMultiplier: 2 },
  },

  // ── Berserker (advanced class) ────────────────────────────────────
  rending_cleave: {
    identifier: 'rending_cleave',
    displayName: 'Rending Cleave',
    description: "Where the berserker's arm falls, more than one enemy learns to regret being close.",
    manaPointCost: 6,
    targetingRange: 1,
    areaOfEffectRadius: 1,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'physical', powerMultiplier: 1.4 },
  },
  unbound_fury: {
    identifier: 'unbound_fury',
    displayName: 'Unbound Fury',
    description: 'Not frenzy this time — pure, aimed, monstrous strength.',
    manaPointCost: 7,
    targetingRange: 0,
    areaOfEffectRadius: 0,
    targetTeam: 'self',
    effect: { kind: 'statModifier', statistic: 'attack', amount: 8, durationTurns: 3 },
  },
} satisfies Record<string, SkillDefinition>;

/**
 * Every valid skill identifier, derived from the pool above — content
 * files reference skills through this type so a typo'd identifier is a
 * compile error, not a mid-battle surprise. The sim layer keeps plain
 * `string` (it must not depend on content).
 */
export type SkillIdentifier = keyof typeof SKILL_ENTRIES;

export const SKILLS: Record<string, SkillDefinition> = SKILL_ENTRIES;
