import type { SkillDefinition } from '../sim/battle/SkillDefinition';

/**
 * The shared skill pool (PRD §7): skills are defined once and referenced by
 * any class or monster that knows them.
 */
export const SKILLS: Record<string, SkillDefinition> = {
  basic_attack: {
    identifier: 'basic_attack',
    displayName: 'Attack',
    description: 'A standard strike with the equipped weapon.',
    manaPointCost: 0,
    targetingRange: 1,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'physical', powerMultiplier: 1.0 },
  },

  // ── Warrior ────────────────────────────────────────────────────────────
  power_strike: {
    identifier: 'power_strike',
    displayName: 'Power Strike',
    description: 'A heavy two-handed blow dealing half again normal damage.',
    manaPointCost: 4,
    targetingRange: 1,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'physical', powerMultiplier: 1.5 },
  },
  war_cry: {
    identifier: 'war_cry',
    displayName: 'War Cry',
    description: 'A rallying roar that raises the user’s attack for three turns.',
    manaPointCost: 3,
    targetingRange: 0,
    areaOfEffectRadius: 0,
    targetTeam: 'self',
    effect: { kind: 'statModifier', statistic: 'attack', amount: 4, durationTurns: 3 },
  },

  // ── Thief ──────────────────────────────────────────────────────────────
  flanking_strike: {
    identifier: 'flanking_strike',
    displayName: 'Flanking Strike',
    description: 'A precise cut that punishes exposed sides and backs.',
    manaPointCost: 3,
    targetingRange: 1,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: {
      kind: 'damage',
      damageSource: 'physical',
      powerMultiplier: 1.1,
      flankingPowerBonus: 0.6,
    },
  },
  thrown_dagger: {
    identifier: 'thrown_dagger',
    displayName: 'Thrown Dagger',
    description: 'A dagger hurled at a target up to three tiles away.',
    manaPointCost: 2,
    targetingRange: 3,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'physical', powerMultiplier: 0.8 },
  },

  // ── Mage ───────────────────────────────────────────────────────────────
  fire_bolt: {
    identifier: 'fire_bolt',
    displayName: 'Fire Bolt',
    description: 'A searing bolt of Kosh’s element hurled at one target.',
    manaPointCost: 5,
    targetingRange: 4,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'magical', powerMultiplier: 1.4, element: 'fire' },
  },
  flame_burst: {
    identifier: 'flame_burst',
    displayName: 'Flame Burst',
    description: 'An eruption of fire that scorches the target tile and its surroundings.',
    manaPointCost: 8,
    targetingRange: 3,
    areaOfEffectRadius: 1,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'magical', powerMultiplier: 1.0, element: 'fire' },
  },

  // ── Thief (status) ────────────────────────────────────────────────────
  venom_strike: {
    identifier: 'venom_strike',
    displayName: 'Venom Strike',
    description: 'A blade coated in a fast-acting toxin. The wound festers for three turns.',
    manaPointCost: 4,
    targetingRange: 1,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'statusEffect', statusEffect: 'poison', durationTurns: 3 },
  },
  smoke_dart: {
    identifier: 'smoke_dart',
    displayName: 'Smoke Dart',
    description: "A blinding dart that clouds the target's vision for three turns.",
    manaPointCost: 4,
    targetingRange: 3,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'statusEffect', statusEffect: 'blind', durationTurns: 3 },
  },

  // ── Mage (status) ──────────────────────────────────────────────────────
  leaden_curse: {
    identifier: 'leaden_curse',
    displayName: 'Leaden Curse',
    description: 'A curse of leaden weight that drags at the target\'s every motion, slowing its turns.',
    manaPointCost: 6,
    targetingRange: 3,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'statusEffect', statusEffect: 'slow', durationTurns: 3 },
  },
  quickening: {
    identifier: 'quickening',
    displayName: 'Quickening',
    description: 'An incantation that quickens an ally\'s steps until the battle\'s rhythm bends around them.',
    manaPointCost: 8,
    targetingRange: 3,
    areaOfEffectRadius: 0,
    targetTeam: 'allies',
    effect: { kind: 'statusEffect', statusEffect: 'haste', durationTurns: 3 },
  },
  sleep_dust: {
    identifier: 'sleep_dust',
    displayName: 'Sleep Dust',
    description: 'A cloud of bewitched powder settles over one target, pulling them into a deep slumber.',
    manaPointCost: 7,
    targetingRange: 3,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'statusEffect', statusEffect: 'sleep', durationTurns: 2 },
  },

  // ── Warrior (earth) ────────────────────────────────────────────────────
  earth_spike: {
    identifier: 'earth_spike',
    displayName: 'Earth Spike',
    description: 'A fist driven into the ground calls up a spike of Taurk\'s stone beneath the target.',
    manaPointCost: 6,
    targetingRange: 2,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'physical', powerMultiplier: 1.3, element: 'earth' },
  },

  // ── Mage (water) ───────────────────────────────────────────────────────
  frost_bolt: {
    identifier: 'frost_bolt',
    displayName: 'Frost Bolt',
    description: 'A shard of Yiern\'s frozen breath, hurled with cutting precision.',
    manaPointCost: 5,
    targetingRange: 4,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'magical', powerMultiplier: 1.4, element: 'water' },
  },

  // ── Priest ─────────────────────────────────────────────────────────────
  first_aid: {
    identifier: 'first_aid',
    displayName: 'First Aid',
    description: 'A prayer of mending that restores an ally’s hit points.',
    manaPointCost: 4,
    targetingRange: 3,
    areaOfEffectRadius: 0,
    targetTeam: 'allies',
    effect: { kind: 'heal', powerMultiplier: 1.5 },
  },
  sacred_bolt: {
    identifier: 'sacred_bolt',
    displayName: 'Sacred Bolt',
    description: 'A lance of Hort’s light. Devastating against the unliving.',
    manaPointCost: 5,
    targetingRange: 3,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'magical', powerMultiplier: 1.2, element: 'sacred' },
  },

  // ── Priest (wards) ─────────────────────────────────────────────────────
  mending_prayer: {
    identifier: 'mending_prayer',
    displayName: 'Mending Prayer',
    description: 'A sustained prayer of mending — the ally\'s wounds keep knitting closed at the start of each of their turns.',
    manaPointCost: 5,
    targetingRange: 3,
    areaOfEffectRadius: 0,
    targetTeam: 'allies',
    effect: { kind: 'statusEffect', statusEffect: 'regen', durationTurns: 3 },
  },
  ward_of_steel: {
    identifier: 'ward_of_steel',
    displayName: 'Ward of Steel',
    description: 'A ward against blade, claw, and tusk — physical blows lose much of their force.',
    manaPointCost: 5,
    targetingRange: 3,
    areaOfEffectRadius: 0,
    targetTeam: 'allies',
    effect: { kind: 'statusEffect', statusEffect: 'protect', durationTurns: 3 },
  },
  ward_of_faith: {
    identifier: 'ward_of_faith',
    displayName: 'Ward of Faith',
    description: 'A ward woven of faith that dampens hostile magic before it lands.',
    manaPointCost: 5,
    targetingRange: 3,
    areaOfEffectRadius: 0,
    targetTeam: 'allies',
    effect: { kind: 'statusEffect', statusEffect: 'shell', durationTurns: 3 },
  },

  // ── Equipment-bound (PRD §7 — granted by gear, mastered through use) ──
  cleaving_arc: {
    identifier: 'cleaving_arc',
    displayName: 'Cleaving Arc',
    description: 'A wide, tusk-heavy sweep that carries through everything beside the first target.',
    manaPointCost: 5,
    targetingRange: 1,
    areaOfEffectRadius: 1,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'physical', powerMultiplier: 1.1 },
  },
  shadow_fang: {
    identifier: 'shadow_fang',
    displayName: 'Shadow Fang',
    description: 'A werecat cut taught knife-to-hand: barely a scratch from the front, ruinous from behind.',
    manaPointCost: 4,
    targetingRange: 1,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: {
      kind: 'damage',
      damageSource: 'physical',
      powerMultiplier: 0.9,
      flankingPowerBonus: 0.9,
    },
  },
  tide_surge: {
    identifier: 'tide_surge',
    displayName: 'Tide Surge',
    description: 'Yiern\'s water called up as a single swell that breaks over the target and its neighbors.',
    manaPointCost: 8,
    targetingRange: 3,
    areaOfEffectRadius: 1,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'magical', powerMultiplier: 1.1, element: 'water' },
  },
  dawns_mercy: {
    identifier: 'dawns_mercy',
    displayName: 'Dawn\'s Mercy',
    description: 'A Hortian prayer of first light that mends every ally standing close together.',
    manaPointCost: 8,
    targetingRange: 3,
    areaOfEffectRadius: 1,
    targetTeam: 'allies',
    effect: { kind: 'heal', powerMultiplier: 1.2 },
  },

  // ── Creatures of the Darkness ──────────────────────────────────────────
  savage_bite: {
    identifier: 'savage_bite',
    displayName: 'Savage Bite',
    description: 'Twisted fangs tear at the target.',
    manaPointCost: 2,
    targetingRange: 1,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'physical', powerMultiplier: 1.25 },
  },
  rock_slam: {
    identifier: 'rock_slam',
    displayName: 'Rock Slam',
    description: 'A living boulder brings its whole mass down on the target.',
    manaPointCost: 3,
    targetingRange: 1,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'physical', powerMultiplier: 1.5 },
  },
  root_lash: {
    identifier: 'root_lash',
    displayName: 'Root Lash',
    description: 'A gnarled root whips out at a target two tiles away.',
    manaPointCost: 2,
    targetingRange: 2,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'physical', powerMultiplier: 1.1, element: 'earth' },
  },
  goring_charge: {
    identifier: 'goring_charge',
    displayName: 'Goring Charge',
    description: 'Twisted tusks slam home with the boar’s full weight behind them.',
    manaPointCost: 3,
    targetingRange: 1,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'physical', powerMultiplier: 1.4 },
  },
  dark_bolt: {
    identifier: 'dark_bolt',
    displayName: 'Dark Bolt',
    description: 'A mote of the unnamed god’s element, flung cold and silent.',
    manaPointCost: 4,
    targetingRange: 3,
    areaOfEffectRadius: 0,
    targetTeam: 'enemies',
    effect: { kind: 'damage', damageSource: 'magical', powerMultiplier: 1.2, element: 'dark' },
  },
};
