import type { AdvancedClassDefinition } from '../../sim/units/UnitDefinitions';
import {
  PURE_ADVANCED_CLASS_UNLOCK_LEVEL,
  HYBRID_PRIMARY_UNLOCK_LEVEL,
  HYBRID_SECONDARY_UNLOCK_LEVEL,
} from './shared';

/** Human-exclusive advanced classes (PRD §4 — 7 classes; 13 total with shared). */
export const HUMAN_ADVANCED_CLASSES: Record<string, AdvancedClassDefinition> = {
  dragoon: {
    identifier: 'dragoon',
    displayName: 'Dragoon',
    description: 'A warrior who turned the battlefield vertical. Dragoons leap over obstacles and enemies alike, striking from above with force no grounded fighter can match.',
    prerequisite: {
      primaryBaseClass: 'warrior',
      primaryBaseClassLevel: PURE_ADVANCED_CLASS_UNLOCK_LEVEL,
    },
    statisticsAtLevelOne: {
      hitPointsMaximum: 30,
      manaPointsMaximum: 8,
      attack: 11,
      defense: 8,
      magicPower: 2,
      magicResistance: 4,
      speed: 7,
      movementRange: 4,
      jumpHeight: 3,
      evasion: 0.05,
    },
    statisticGrowthPerLevel: {
      hitPointsMaximum: 7,
      manaPointsMaximum: 1,
      attack: 2,
      defense: 1.5,
      magicResistance: 0.5,
      speed: 0.4,
    },
    skills: [],
  },

  black_mage: {
    identifier: 'black_mage',
    displayName: 'Black Mage',
    description: 'Pure elemental destruction in Human form. Black Mages trade survivability for the highest offensive magic power attainable — pointed squarely at what needs to burn.',
    prerequisite: {
      primaryBaseClass: 'mage',
      primaryBaseClassLevel: PURE_ADVANCED_CLASS_UNLOCK_LEVEL,
    },
    statisticsAtLevelOne: {
      hitPointsMaximum: 18,
      manaPointsMaximum: 28,
      attack: 3,
      defense: 3,
      magicPower: 13,
      magicResistance: 9,
      speed: 7,
      movementRange: 3,
      jumpHeight: 1,
      evasion: 0.05,
    },
    statisticGrowthPerLevel: {
      hitPointsMaximum: 2.5,
      manaPointsMaximum: 5,
      defense: 0.5,
      magicPower: 2.5,
      magicResistance: 1.5,
      speed: 0.4,
    },
    skills: [],
  },

  illusionist: {
    identifier: 'illusionist',
    displayName: 'Illusionist',
    description: 'A mage who bends perception and shatters enemy focus. Illusionists favor confusion and mental disruption over direct destruction.',
    prerequisite: {
      primaryBaseClass: 'mage',
      primaryBaseClassLevel: PURE_ADVANCED_CLASS_UNLOCK_LEVEL,
    },
    statisticsAtLevelOne: {
      hitPointsMaximum: 20,
      manaPointsMaximum: 26,
      attack: 3,
      defense: 4,
      magicPower: 11,
      magicResistance: 9,
      speed: 7,
      movementRange: 3,
      jumpHeight: 1,
      evasion: 0.07,
    },
    statisticGrowthPerLevel: {
      hitPointsMaximum: 3,
      manaPointsMaximum: 4,
      defense: 0.5,
      magicPower: 2,
      magicResistance: 1.5,
      speed: 0.4,
    },
    skills: [],
  },

  bishop: {
    identifier: 'bishop',
    displayName: 'Bishop',
    description: 'A devoted servant of Hort whose prayers can restore the dying and strike down the impure. Bishops amplify healing and Sacred power beyond any ordinary priest.',
    prerequisite: {
      primaryBaseClass: 'priest',
      primaryBaseClassLevel: PURE_ADVANCED_CLASS_UNLOCK_LEVEL,
    },
    statisticsAtLevelOne: {
      hitPointsMaximum: 22,
      manaPointsMaximum: 26,
      attack: 4,
      defense: 5,
      magicPower: 11,
      magicResistance: 11,
      speed: 7,
      movementRange: 3,
      jumpHeight: 1,
      evasion: 0.05,
    },
    statisticGrowthPerLevel: {
      hitPointsMaximum: 4,
      manaPointsMaximum: 4,
      attack: 0.5,
      defense: 1,
      magicPower: 2,
      magicResistance: 2,
      speed: 0.4,
    },
    skills: [],
  },

  paladin: {
    identifier: 'paladin',
    displayName: 'Paladin',
    description: 'A holy warrior blessed by Hort to serve the church on the battlefield. Equal parts sword and healer, Paladins endure punishments that would break anyone else.',
    prerequisite: {
      primaryBaseClass: 'warrior',
      primaryBaseClassLevel: HYBRID_PRIMARY_UNLOCK_LEVEL,
      secondaryBaseClass: 'priest',
      secondaryBaseClassLevel: HYBRID_SECONDARY_UNLOCK_LEVEL,
    },
    statisticsAtLevelOne: {
      hitPointsMaximum: 32,
      manaPointsMaximum: 16,
      attack: 10,
      defense: 10,
      magicPower: 6,
      magicResistance: 8,
      speed: 7,
      movementRange: 4,
      jumpHeight: 1,
      evasion: 0.05,
    },
    statisticGrowthPerLevel: {
      hitPointsMaximum: 7,
      manaPointsMaximum: 2,
      attack: 2,
      defense: 2,
      magicPower: 1,
      magicResistance: 1,
      speed: 0.4,
    },
    skills: [],
  },

  rune_knight: {
    identifier: 'rune_knight',
    displayName: 'Rune Knight',
    description: 'A warrior who learned to etch magic into steel. Rune Knights combine martial skill with enchanted strikes — hits that carry weight both physical and arcane.',
    prerequisite: {
      primaryBaseClass: 'warrior',
      primaryBaseClassLevel: HYBRID_PRIMARY_UNLOCK_LEVEL,
      secondaryBaseClass: 'mage',
      secondaryBaseClassLevel: HYBRID_SECONDARY_UNLOCK_LEVEL,
    },
    statisticsAtLevelOne: {
      hitPointsMaximum: 28,
      manaPointsMaximum: 18,
      attack: 10,
      defense: 7,
      magicPower: 7,
      magicResistance: 6,
      speed: 7,
      movementRange: 4,
      jumpHeight: 1,
      evasion: 0.05,
    },
    statisticGrowthPerLevel: {
      hitPointsMaximum: 6,
      manaPointsMaximum: 2.5,
      attack: 1.5,
      defense: 1.5,
      magicPower: 1.5,
      magicResistance: 1,
      speed: 0.4,
    },
    skills: [],
  },

  spellthief: {
    identifier: 'spellthief',
    displayName: 'Spellthief',
    description: 'A rogue with a gift for magic — or a talent for taking it. Spellthieves weave speed and arcane cunning into an unpredictable fighting style.',
    prerequisite: {
      primaryBaseClass: 'thief',
      primaryBaseClassLevel: HYBRID_PRIMARY_UNLOCK_LEVEL,
      secondaryBaseClass: 'mage',
      secondaryBaseClassLevel: HYBRID_SECONDARY_UNLOCK_LEVEL,
    },
    statisticsAtLevelOne: {
      hitPointsMaximum: 22,
      manaPointsMaximum: 18,
      attack: 8,
      defense: 5,
      magicPower: 8,
      magicResistance: 5,
      speed: 10,
      movementRange: 5,
      jumpHeight: 2,
      evasion: 0.12,
    },
    statisticGrowthPerLevel: {
      hitPointsMaximum: 4,
      manaPointsMaximum: 2.5,
      attack: 1.5,
      defense: 0.5,
      magicPower: 1.5,
      magicResistance: 1,
      speed: 0.6,
    },
    skills: [],
  },

  inquisitor: {
    identifier: 'inquisitor',
    displayName: 'Inquisitor',
    description: 'An agent of the Hortian church who hunts the corrupt and the unholy. Fast, faithful, and relentless — part interrogator, part executioner, all conviction.',
    prerequisite: {
      primaryBaseClass: 'thief',
      primaryBaseClassLevel: HYBRID_PRIMARY_UNLOCK_LEVEL,
      secondaryBaseClass: 'priest',
      secondaryBaseClassLevel: HYBRID_SECONDARY_UNLOCK_LEVEL,
    },
    statisticsAtLevelOne: {
      hitPointsMaximum: 24,
      manaPointsMaximum: 18,
      attack: 8,
      defense: 6,
      magicPower: 7,
      magicResistance: 7,
      speed: 9,
      movementRange: 4,
      jumpHeight: 2,
      evasion: 0.1,
    },
    statisticGrowthPerLevel: {
      hitPointsMaximum: 4,
      manaPointsMaximum: 2.5,
      attack: 1.5,
      defense: 1,
      magicPower: 1.5,
      magicResistance: 1.5,
      speed: 0.5,
    },
    skills: [],
  },
};
