import type { AdvancedClassDefinition } from '../../sim/units/UnitDefinitions';
import {
  PURE_ADVANCED_CLASS_UNLOCK_LEVEL,
  HYBRID_PRIMARY_UNLOCK_LEVEL,
  HYBRID_SECONDARY_UNLOCK_LEVEL,
} from './shared';

/** Undead-exclusive advanced classes (PRD §4 — 6 classes; 7 total with shared). */
export const UNDEAD_ADVANCED_CLASSES: Record<string, AdvancedClassDefinition> = {
  dread_knight: {
    identifier: 'dread_knight',
    displayName: 'Dread Knight',
    prerequisite: {
      primaryBaseClass: 'warrior',
      primaryBaseClassLevel: PURE_ADVANCED_CLASS_UNLOCK_LEVEL,
    },
    statisticsAtLevelOne: {
      hitPointsMaximum: 34,
      manaPointsMaximum: 14,
      attack: 12,
      defense: 8,
      magicPower: 4,
      magicResistance: 5,
      speed: 5,
      movementRange: 4,
      jumpHeight: 1,
      evasion: 0.03,
    },
    statisticGrowthPerLevel: {
      hitPointsMaximum: 7,
      manaPointsMaximum: 1.5,
      attack: 2.5,
      defense: 1.5,
      magicPower: 0.5,
      magicResistance: 0.5,
      speed: 0.3,
    },
    skillIdentifiers: [],
  },

  pyromancer: {
    identifier: 'pyromancer',
    displayName: 'Pyromancer',
    prerequisite: {
      primaryBaseClass: 'mage',
      primaryBaseClassLevel: PURE_ADVANCED_CLASS_UNLOCK_LEVEL,
    },
    statisticsAtLevelOne: {
      hitPointsMaximum: 18,
      manaPointsMaximum: 30,
      attack: 3,
      defense: 3,
      magicPower: 15,
      magicResistance: 8,
      speed: 6,
      movementRange: 3,
      jumpHeight: 1,
      evasion: 0.03,
    },
    statisticGrowthPerLevel: {
      hitPointsMaximum: 2.5,
      manaPointsMaximum: 6,
      defense: 0.5,
      magicPower: 3,
      magicResistance: 1.5,
      speed: 0.3,
    },
    skillIdentifiers: [],
  },

  necromancer: {
    identifier: 'necromancer',
    displayName: 'Necromancer',
    prerequisite: {
      primaryBaseClass: 'mage',
      primaryBaseClassLevel: PURE_ADVANCED_CLASS_UNLOCK_LEVEL,
    },
    statisticsAtLevelOne: {
      hitPointsMaximum: 20,
      manaPointsMaximum: 28,
      attack: 3,
      defense: 3,
      magicPower: 12,
      magicResistance: 9,
      speed: 6,
      movementRange: 3,
      jumpHeight: 1,
      evasion: 0.03,
    },
    statisticGrowthPerLevel: {
      hitPointsMaximum: 3,
      manaPointsMaximum: 5,
      defense: 0.5,
      magicPower: 2.5,
      magicResistance: 1.5,
      speed: 0.3,
    },
    skillIdentifiers: [],
  },

  revenant: {
    identifier: 'revenant',
    displayName: 'Revenant',
    prerequisite: {
      primaryBaseClass: 'warrior',
      primaryBaseClassLevel: HYBRID_PRIMARY_UNLOCK_LEVEL,
      secondaryBaseClass: 'thief',
      secondaryBaseClassLevel: HYBRID_SECONDARY_UNLOCK_LEVEL,
    },
    statisticsAtLevelOne: {
      hitPointsMaximum: 30,
      manaPointsMaximum: 12,
      attack: 12,
      defense: 7,
      magicPower: 3,
      magicResistance: 4,
      speed: 7,
      movementRange: 4,
      jumpHeight: 1,
      evasion: 0.08,
    },
    statisticGrowthPerLevel: {
      hitPointsMaximum: 6,
      manaPointsMaximum: 1.5,
      attack: 2.5,
      defense: 1,
      magicPower: 0.5,
      magicResistance: 0.5,
      speed: 0.4,
    },
    skillIdentifiers: [],
  },

  ashguard: {
    identifier: 'ashguard',
    displayName: 'Ashguard',
    prerequisite: {
      primaryBaseClass: 'warrior',
      primaryBaseClassLevel: HYBRID_PRIMARY_UNLOCK_LEVEL,
      secondaryBaseClass: 'mage',
      secondaryBaseClassLevel: HYBRID_SECONDARY_UNLOCK_LEVEL,
    },
    statisticsAtLevelOne: {
      hitPointsMaximum: 30,
      manaPointsMaximum: 18,
      attack: 11,
      defense: 9,
      magicPower: 8,
      magicResistance: 7,
      speed: 5,
      movementRange: 3,
      jumpHeight: 1,
      evasion: 0.02,
    },
    statisticGrowthPerLevel: {
      hitPointsMaximum: 6,
      manaPointsMaximum: 2.5,
      attack: 2,
      defense: 2,
      magicPower: 1.5,
      magicResistance: 1,
      speed: 0.3,
    },
    skillIdentifiers: [],
  },

  wraith: {
    identifier: 'wraith',
    displayName: 'Wraith',
    prerequisite: {
      primaryBaseClass: 'thief',
      primaryBaseClassLevel: HYBRID_PRIMARY_UNLOCK_LEVEL,
      secondaryBaseClass: 'mage',
      secondaryBaseClassLevel: HYBRID_SECONDARY_UNLOCK_LEVEL,
    },
    statisticsAtLevelOne: {
      hitPointsMaximum: 22,
      manaPointsMaximum: 20,
      attack: 8,
      defense: 4,
      magicPower: 9,
      magicResistance: 6,
      speed: 9,
      movementRange: 5,
      jumpHeight: 2,
      evasion: 0.18,
    },
    statisticGrowthPerLevel: {
      hitPointsMaximum: 3.5,
      manaPointsMaximum: 3,
      attack: 1.5,
      defense: 0.5,
      magicPower: 2,
      magicResistance: 1,
      speed: 0.6,
    },
    skillIdentifiers: [],
  },
};
