import type { AdvancedClassDefinition } from '../../sim/units/UnitDefinitions';
import {
  PURE_ADVANCED_CLASS_UNLOCK_LEVEL,
  HYBRID_PRIMARY_UNLOCK_LEVEL,
  HYBRID_SECONDARY_UNLOCK_LEVEL,
} from './shared';

/** Werecat-exclusive advanced classes (PRD §4 — 6 classes; 10 total with shared). */
export const WERECAT_ADVANCED_CLASSES: Record<string, AdvancedClassDefinition> = {
  shadowdancer: {
    identifier: 'shadowdancer',
    displayName: 'Shadowdancer',
    prerequisite: {
      primaryBaseClass: 'thief',
      primaryBaseClassLevel: PURE_ADVANCED_CLASS_UNLOCK_LEVEL,
    },
    statisticsAtLevelOne: {
      hitPointsMaximum: 24,
      manaPointsMaximum: 14,
      attack: 8,
      defense: 5,
      magicPower: 4,
      magicResistance: 4,
      speed: 12,
      movementRange: 6,
      jumpHeight: 2,
      evasion: 0.25,
    },
    statisticGrowthPerLevel: {
      hitPointsMaximum: 4,
      manaPointsMaximum: 1.5,
      attack: 1.5,
      defense: 0.5,
      speed: 0.8,
      evasion: 0.008,
    },
    skillIdentifiers: [],
  },

  galeweaver: {
    identifier: 'galeweaver',
    displayName: 'Galeweaver',
    prerequisite: {
      primaryBaseClass: 'mage',
      primaryBaseClassLevel: PURE_ADVANCED_CLASS_UNLOCK_LEVEL,
    },
    statisticsAtLevelOne: {
      hitPointsMaximum: 20,
      manaPointsMaximum: 26,
      attack: 3,
      defense: 4,
      magicPower: 11,
      magicResistance: 8,
      speed: 8,
      movementRange: 4,
      jumpHeight: 2,
      evasion: 0.08,
    },
    statisticGrowthPerLevel: {
      hitPointsMaximum: 3,
      manaPointsMaximum: 4,
      defense: 0.5,
      magicPower: 2,
      magicResistance: 1.5,
      speed: 0.5,
    },
    skillIdentifiers: [],
  },

  windwanderer: {
    identifier: 'windwanderer',
    displayName: 'Windwanderer',
    prerequisite: {
      primaryBaseClass: 'warrior',
      primaryBaseClassLevel: HYBRID_PRIMARY_UNLOCK_LEVEL,
      secondaryBaseClass: 'mage',
      secondaryBaseClassLevel: HYBRID_SECONDARY_UNLOCK_LEVEL,
    },
    statisticsAtLevelOne: {
      hitPointsMaximum: 26,
      manaPointsMaximum: 16,
      attack: 10,
      defense: 6,
      magicPower: 7,
      magicResistance: 5,
      speed: 10,
      movementRange: 5,
      jumpHeight: 2,
      evasion: 0.1,
    },
    statisticGrowthPerLevel: {
      hitPointsMaximum: 5,
      manaPointsMaximum: 2,
      attack: 2,
      defense: 1,
      magicPower: 1.5,
      magicResistance: 1,
      speed: 0.7,
    },
    skillIdentifiers: [],
  },

  priest_of_the_8_lives: {
    identifier: 'priest_of_the_8_lives',
    displayName: 'Priest of the 8 Lives',
    prerequisite: {
      primaryBaseClass: 'warrior',
      primaryBaseClassLevel: HYBRID_PRIMARY_UNLOCK_LEVEL,
      secondaryBaseClass: 'priest',
      secondaryBaseClassLevel: HYBRID_SECONDARY_UNLOCK_LEVEL,
    },
    statisticsAtLevelOne: {
      hitPointsMaximum: 28,
      manaPointsMaximum: 16,
      attack: 9,
      defense: 7,
      magicPower: 7,
      magicResistance: 8,
      speed: 8,
      movementRange: 4,
      jumpHeight: 2,
      evasion: 0.08,
    },
    statisticGrowthPerLevel: {
      hitPointsMaximum: 6,
      manaPointsMaximum: 2,
      attack: 2,
      defense: 1.5,
      magicPower: 1.5,
      magicResistance: 1.5,
      speed: 0.5,
    },
    skillIdentifiers: [],
  },

  phantom: {
    identifier: 'phantom',
    displayName: 'Phantom',
    prerequisite: {
      primaryBaseClass: 'thief',
      primaryBaseClassLevel: HYBRID_PRIMARY_UNLOCK_LEVEL,
      secondaryBaseClass: 'mage',
      secondaryBaseClassLevel: HYBRID_SECONDARY_UNLOCK_LEVEL,
    },
    statisticsAtLevelOne: {
      hitPointsMaximum: 22,
      manaPointsMaximum: 18,
      attack: 8,
      defense: 4,
      magicPower: 8,
      magicResistance: 5,
      speed: 12,
      movementRange: 6,
      jumpHeight: 3,
      evasion: 0.2,
    },
    statisticGrowthPerLevel: {
      hitPointsMaximum: 4,
      manaPointsMaximum: 2.5,
      attack: 1.5,
      defense: 0.5,
      magicPower: 1.5,
      magicResistance: 0.5,
      speed: 0.7,
    },
    skillIdentifiers: [],
  },

  shrine_warden: {
    identifier: 'shrine_warden',
    displayName: 'Shrine Warden',
    prerequisite: {
      primaryBaseClass: 'thief',
      primaryBaseClassLevel: HYBRID_PRIMARY_UNLOCK_LEVEL,
      secondaryBaseClass: 'priest',
      secondaryBaseClassLevel: HYBRID_SECONDARY_UNLOCK_LEVEL,
    },
    statisticsAtLevelOne: {
      hitPointsMaximum: 24,
      manaPointsMaximum: 18,
      attack: 7,
      defense: 6,
      magicPower: 7,
      magicResistance: 8,
      speed: 10,
      movementRange: 5,
      jumpHeight: 2,
      evasion: 0.14,
    },
    statisticGrowthPerLevel: {
      hitPointsMaximum: 4,
      manaPointsMaximum: 2.5,
      attack: 1.5,
      defense: 1,
      magicPower: 1.5,
      magicResistance: 1.5,
      speed: 0.6,
    },
    skillIdentifiers: [],
  },
};
