import type { AdvancedClassDefinition } from '../../sim/units/UnitDefinitions';
import {
  PURE_ADVANCED_CLASS_UNLOCK_LEVEL,
  HYBRID_PRIMARY_UNLOCK_LEVEL,
  HYBRID_SECONDARY_UNLOCK_LEVEL,
} from './shared';

/** Werecat-exclusive advanced classes (PRD §4 — 6 classes; 10 total with shared). */
export const WERECAT_ADVANCED_CLASSES: Record<string, AdvancedClassDefinition> = {
  shadowdancer: {
    identifier: 'shadowdancer',
    displayName: 'Shadowdancer',
    description: 'A Werecat who learned to move with shadow itself. Shadowdancers are nearly impossible to pin down, striking and disappearing before any retaliation can land.',
    prerequisite: {
      primaryBaseClass: 'thief',
      primaryBaseClassLevel: PURE_ADVANCED_CLASS_UNLOCK_LEVEL,
    },
    statisticsAtLevelOne: {
      hitPointsMaximum: 24,
      manaPointsMaximum: 14,
      attack: 8,
      defense: 5,
      magicPower: 4,
      magicResistance: 4,
      speed: 12,
      movementRange: 6,
      jumpHeight: 2,
      evasion: 0.25,
    },
    statisticGrowthPerLevel: {
      hitPointsMaximum: 4,
      manaPointsMaximum: 1.5,
      attack: 1.5,
      defense: 0.5,
      speed: 0.8,
      evasion: 0.008,
    },
    skills: [],
  },

  galeweaver: {
    identifier: 'galeweaver',
    displayName: 'Galeweaver',
    description: 'A Werecat mage devoted to Breir\'s wind. Galeweavers reshape the field by controlling air, punishing clustered enemies and rewarding allies who keep moving.',
    prerequisite: {
      primaryBaseClass: 'mage',
      primaryBaseClassLevel: PURE_ADVANCED_CLASS_UNLOCK_LEVEL,
    },
    statisticsAtLevelOne: {
      hitPointsMaximum: 20,
      manaPointsMaximum: 26,
      attack: 3,
      defense: 4,
      magicPower: 11,
      magicResistance: 8,
      speed: 8,
      movementRange: 4,
      jumpHeight: 2,
      evasion: 0.08,
    },
    statisticGrowthPerLevel: {
      hitPointsMaximum: 3,
      manaPointsMaximum: 4,
      defense: 0.5,
      magicPower: 2,
      magicResistance: 1.5,
      speed: 0.5,
    },
    skills: [],
  },

  windwanderer: {
    identifier: 'windwanderer',
    displayName: 'Windwanderer',
    description: 'A Werecat warrior who channels Breir\'s wind into every strike and step. As fast as the gale they emulate — difficult to hit, impossible to outrun.',
    prerequisite: {
      primaryBaseClass: 'warrior',
      primaryBaseClassLevel: HYBRID_PRIMARY_UNLOCK_LEVEL,
      secondaryBaseClass: 'mage',
      secondaryBaseClassLevel: HYBRID_SECONDARY_UNLOCK_LEVEL,
    },
    statisticsAtLevelOne: {
      hitPointsMaximum: 26,
      manaPointsMaximum: 16,
      attack: 10,
      defense: 6,
      magicPower: 7,
      magicResistance: 5,
      speed: 10,
      movementRange: 5,
      jumpHeight: 2,
      evasion: 0.1,
    },
    statisticGrowthPerLevel: {
      hitPointsMaximum: 5,
      manaPointsMaximum: 2,
      attack: 2,
      defense: 1,
      magicPower: 1.5,
      magicResistance: 1,
      speed: 0.7,
    },
    skills: [],
  },

  priest_of_the_8_lives: {
    identifier: 'priest_of_the_8_lives',
    displayName: 'Priest of the 8 Lives',
    description: 'A Werecat who devoted one of their eight lives to the shrines of Breir and Taurk. They carry earth\'s endurance and wind\'s swiftness as blessings into every fight.',
    prerequisite: {
      primaryBaseClass: 'warrior',
      primaryBaseClassLevel: HYBRID_PRIMARY_UNLOCK_LEVEL,
      secondaryBaseClass: 'priest',
      secondaryBaseClassLevel: HYBRID_SECONDARY_UNLOCK_LEVEL,
    },
    statisticsAtLevelOne: {
      hitPointsMaximum: 28,
      manaPointsMaximum: 16,
      attack: 9,
      defense: 7,
      magicPower: 7,
      magicResistance: 8,
      speed: 8,
      movementRange: 4,
      jumpHeight: 2,
      evasion: 0.08,
    },
    statisticGrowthPerLevel: {
      hitPointsMaximum: 6,
      manaPointsMaximum: 2,
      attack: 2,
      defense: 1.5,
      magicPower: 1.5,
      magicResistance: 1.5,
      speed: 0.5,
    },
    skills: [],
  },

  phantom: {
    identifier: 'phantom',
    displayName: 'Phantom',
    description: 'A Werecat who perfected wind-image techniques, leaving after-images that baffle attackers. Phantoms strike from angles that shouldn\'t exist and vanish before the blow lands.',
    prerequisite: {
      primaryBaseClass: 'thief',
      primaryBaseClassLevel: HYBRID_PRIMARY_UNLOCK_LEVEL,
      secondaryBaseClass: 'mage',
      secondaryBaseClassLevel: HYBRID_SECONDARY_UNLOCK_LEVEL,
    },
    statisticsAtLevelOne: {
      hitPointsMaximum: 22,
      manaPointsMaximum: 18,
      attack: 8,
      defense: 4,
      magicPower: 8,
      magicResistance: 5,
      speed: 12,
      movementRange: 6,
      jumpHeight: 3,
      evasion: 0.2,
    },
    statisticGrowthPerLevel: {
      hitPointsMaximum: 4,
      manaPointsMaximum: 2.5,
      attack: 1.5,
      defense: 0.5,
      magicPower: 1.5,
      magicResistance: 0.5,
      speed: 0.7,
    },
    skills: [],
  },

  shrine_warden: {
    identifier: 'shrine_warden',
    displayName: 'Shrine Warden',
    description: 'A guardian of Breir\'s and Taurk\'s shrines who fights with the blessings of wind and earth. Wardens protect what is sacred — and make examples of those who threaten it.',
    prerequisite: {
      primaryBaseClass: 'thief',
      primaryBaseClassLevel: HYBRID_PRIMARY_UNLOCK_LEVEL,
      secondaryBaseClass: 'priest',
      secondaryBaseClassLevel: HYBRID_SECONDARY_UNLOCK_LEVEL,
    },
    statisticsAtLevelOne: {
      hitPointsMaximum: 24,
      manaPointsMaximum: 18,
      attack: 7,
      defense: 6,
      magicPower: 7,
      magicResistance: 8,
      speed: 10,
      movementRange: 5,
      jumpHeight: 2,
      evasion: 0.14,
    },
    statisticGrowthPerLevel: {
      hitPointsMaximum: 4,
      manaPointsMaximum: 2.5,
      attack: 1.5,
      defense: 1,
      magicPower: 1.5,
      magicResistance: 1.5,
      speed: 0.6,
    },
    skills: [],
  },
};
